# Generated by Django 2.0.3 on 2018-06-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_id', models.CharField(choices=[('CUIT', 'CUIT'), ('CUIL', 'CUIL')], default='CUIT', max_length=10, verbose_name='CUIT o CUIL')),
                ('numero_id', models.CharField(max_length=20, verbose_name='Número de CUIT/CUIL')),
            ],
        ),
        migrations.CreateModel(
            name='Fisica',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entidades.Persona')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
            ],
            bases=('entidades.persona',),
        ),
        migrations.CreateModel(
            name='Juridica',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entidades.Persona')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
            ],
            bases=('entidades.persona',),
        ),
    ]
